version: '2.4'
services:
  mautrix-signal:
    image: dock.mau.dev/tulir/mautrix-signal:latest
    restart: unless-stopped
    volumes:
    - /var/mautrix-signal:/data
    - /var/signald:/signald
    networks:
    - matrix_net
    - postgrs_net
  signald:
    image: docker.io/finn/signald:latest
    restart: unless-stopped
    volumes:
    - /var/signald:/signald
networks:
  matrix_net:
    name: matrix_net
    driver: bridge
  postgres_net:
    name: postgres_net
    external: true
