version: '2.4'
services:
  nextcloud:
    image: nextcloud:fpm
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: mariadb
      MYSQL_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
      TRUSTED_PROXIES: "cloud.teier.eu 138.201.74.231 172.0.0.1/8"
      APACHE_DISABLE_REWRITE_IP: "1"
      OVERWRITEHOST: "cloud.teier.eu"
      OVERWRITEPROTOCOL: "https"
      OVERWRITEWEBROOT: "/"
      OVERWRITECONADDR: "138.201.74.231"
    networks:
      - "mariadb_net"
      - "nextcloud_net"
    volumes:
      - /var/nextcloud:/var/www/html
  web:
    image: nginx
    restart: always
    ports:
      - 8081:80
    networks:
      - "nextcloud_net"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - nextcloud
networks:
  nextcloud_net:
    name: "nextcloud_net"
    driver: bridge
  mariadb_net:
    name: "mariadb_net"
    external: true
    